// Geçici dosya - büyük replace için
// Bu dosya centralStockView.vue'daki demo verileri unitPrice olmadan içerecek
const demoData = [
  {
    id: 'cs_001',
    productName: 'Dizüstü Bilgisayar',
    productCode: 'NB-001',
    brand: 'Dell',
    category: 'Elektronik',
    currentStock: 50,
    minStock: 10,
    maxStock: 100,
    unit: 'adet',
    lastMovement: new Date().toISOString(),
    lastMovementType: 'IN',
    location: 'A-1-001'
  },
  {
    id: 'cs_002',
    productName: 'Yazılım Lisansı',
    productCode: 'SW-001',
    brand: 'Microsoft',
    category: 'Yazılım',
    currentStock: 200,
    minStock: 20,
    maxStock: 500,
    unit: 'lisans',
    lastMovement: new Date().toISOString(),
    lastMovementType: 'IN',
    location: 'B-1-001'
  },
  {
    id: 'cs_003',
    productName: 'Monitör',
    productCode: 'MON-001',
    brand: 'Samsung',
    category: 'Elektronik',
    currentStock: 5,
    minStock: 15,
    maxStock: 50,
    unit: 'adet',
    lastMovement: new Date().toISOString(),
    lastMovementType: 'OUT',
    location: 'A-2-001'
  },
  {
    id: 'cs_004',
    productName: 'Ofis Sandalyesi',
    productCode: 'CHR-001',
    brand: 'Herman Miller',
    category: 'Mobilya',
    currentStock: 75,
    minStock: 20,
    maxStock: 100,
    unit: 'adet',
    lastMovement: new Date().toISOString(),
    lastMovementType: 'IN',
    location: 'C-1-001'
  },
  {
    id: 'cs_005',
    productName: 'Yazıcı Toneri',
    productCode: 'TNR-001',
    brand: 'HP',
    category: 'Sarf Malzemesi',
    currentStock: 2,
    minStock: 25,
    maxStock: 100,
    unit: 'adet',
    lastMovement: new Date().toISOString(),
    lastMovementType: 'OUT',
    location: 'B-2-001'
  },
  {
    id: 'cs_006',
    productName: 'Ethernet Kablosu',
    productCode: 'CBL-001',
    category: 'Ağ Ekipmanları',
    currentStock: 500,
    minStock: 50,
    maxStock: 1000,
    unit: 'metre',
    lastMovement: new Date().toISOString(),
    lastMovementType: 'IN',
    location: 'A-3-001'
  },
  {
    id: 'cs_007',
    productName: 'Tablet',
    productCode: 'TAB-001',
    brand: 'iPad',
    category: 'Elektronik',
    currentStock: 30,
    minStock: 10,
    maxStock: 50,
    unit: 'adet',
    lastMovement: new Date().toISOString(),
    lastMovementType: 'TRANSFER',
    location: 'A-1-002'
  },
  {
    id: 'cs_008',
    productName: 'Projeksiyon Cihazı',
    productCode: 'PRJ-001',
    brand: 'Epson',
    category: 'Elektronik',
    currentStock: 8,
    minStock: 5,
    maxStock: 20,
    unit: 'adet',
    lastMovement: new Date().toISOString(),
    lastMovementType: 'IN',
    location: 'D-1-001'
  },
  {
    id: 'cs_009',
    productName: 'Sunucu',
    productCode: 'SRV-001',
    brand: 'HP',
    category: 'Sunucu',
    currentStock: 3,
    minStock: 2,
    maxStock: 10,
    unit: 'adet',
    lastMovement: new Date().toISOString(),
    lastMovementType: 'IN',
    location: 'D-1-001'
  },
  {
    id: 'cs_010',
    productName: 'UPS',
    productCode: 'UPS-001',
    brand: 'APC',
    category: 'Güç Sistemleri',
    currentStock: 0,
    minStock: 5,
    maxStock: 20,
    unit: 'adet',
    lastMovement: new Date().toISOString(),
    lastMovementType: 'OUT',
    location: 'C-2-001'
  }
];
